## best score 0.78

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
from tpot import TPOTClassifier
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [15]:
train = pd.read_csv('Data/selected_train.csv')
test = pd.read_csv('Data/selected_test.csv')
val = pd.read_csv('Data/selected_val.csv')

X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [16]:
dist = {'n_neighbors': [3, 5,6,7,8, 9, 10,11, 12, 15, 21]}

In [17]:
clf = KNeighborsClassifier()





grid_search = GridSearchCV(estimator=clf, param_grid=dist, cv=3, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)


best_params = grid_search.best_params_
best_score = grid_search.best_score_
cv_results = grid_search.cv_results_

print("Best Parameters:", best_params)
print("Best Score:", best_score)
print("Best model CV Results:", cv_results["mean_test_score"][grid_search.best_index_])

Fitting 3 folds for each of 11 candidates, totalling 33 fits
[CV] END ......................................n_neighbors=3; total time=   0.8s
[CV] END ......................................n_neighbors=3; total time=   0.8s
[CV] END ......................................n_neighbors=3; total time=   0.8s
[CV] END ......................................n_neighbors=5; total time=   0.8s
[CV] END ......................................n_neighbors=5; total time=   0.8s
[CV] END ......................................n_neighbors=6; total time=   0.9s
[CV] END ......................................n_neighbors=5; total time=   0.9s
[CV] END ......................................n_neighbors=6; total time=   0.9s
[CV] END ......................................n_neighbors=7; total time=   0.7s
[CV] END ......................................n_neighbors=7; total time=   0.7s
[CV] END ......................................n_neighbors=7; total time=   0.7s
[CV] END ......................................n

Best Parameters: {'n_neighbors': 5}  
Best Score: 0.7808670082597412  
Best model CV Results: 0.7808670082597412

In [21]:
#best
best = KNeighborsClassifier(n_neighbors=5)
best.fit(X_train, y_train)
y_pred1 = best.predict(X_val)
class_report1 = classification_report(y_val, y_pred1)
print("Classification Report:\n", class_report1)
conf_matrix1 = confusion_matrix(y_val, y_pred1)
print("\nConfusion Matrix:")
print(conf_matrix1)

Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.78      0.79       525
           1       0.62      0.74      0.67       624
           2       0.74      0.74      0.74       604
           3       0.92      0.94      0.93       714
           4       1.00      1.00      1.00       837
           5       0.61      0.55      0.58       532
           6       0.63      0.56      0.59       523

    accuracy                           0.78      4359
   macro avg       0.76      0.76      0.76      4359
weighted avg       0.78      0.78      0.78      4359


Confusion Matrix:
[[410 102   2   0   0   8   3]
 [ 70 460   7   1   0  68  18]
 [  4  15 444  39   3  27  72]
 [  0   0  27 672   0   2  13]
 [  0   2   1   0 834   0   0]
 [ 22 112  35   0   0 295  68]
 [  4  48  81  16   0  80 294]]
