## best score 0.74 (0.78)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [22]:
train = pd.read_csv('Data/train_with_BMI.csv')
test = pd.read_csv('Data/test_with_BMI.csv')
val = pd.read_csv('Data/val_with_BMI.csv')

X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [23]:
dist = {'n_neighbors': [3, 5,6,7,8, 9, 10,11, 12, 15, 21]}

In [24]:
clf = KNeighborsClassifier()





grid_search = GridSearchCV(estimator=clf, param_grid=dist, cv=3, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)


best_params = grid_search.best_params_
best_score = grid_search.best_score_
cv_results = grid_search.cv_results_

print("Best Parameters:", best_params)
print("Best Score:", best_score)
print("Best model CV Results:", cv_results["mean_test_score"][grid_search.best_index_])

Fitting 3 folds for each of 11 candidates, totalling 33 fits
[CV] END ......................................n_neighbors=3; total time=   1.6s
[CV] END ......................................n_neighbors=3; total time=   1.6s
[CV] END ......................................n_neighbors=3; total time=   1.6s
[CV] END ......................................n_neighbors=5; total time=   1.6s
[CV] END ......................................n_neighbors=5; total time=   1.7s
[CV] END ......................................n_neighbors=5; total time=   1.8s
[CV] END ......................................n_neighbors=6; total time=   1.8s
[CV] END ......................................n_neighbors=6; total time=   2.0s
[CV] END ......................................n_neighbors=6; total time=   1.9s
[CV] END ......................................n_neighbors=7; total time=   1.8s
[CV] END ......................................n_neighbors=7; total time=   1.9s
[CV] END ......................................n

Best Parameters: {'n_neighbors': 10}  
Best Score: 0.7335169491308678  
Best model CV Results: 0.7335169491308678

---
#### z selected features:
Best Parameters: {'n_neighbors': 5}  
Best Score: 0.7808670082597412  
Best model CV Results: 0.7808670082597412
***

In [25]:
#best
best = KNeighborsClassifier(n_neighbors=5)
best.fit(X_train, y_train)
y_pred1 = best.predict(X_val)
class_report1 = classification_report(y_val, y_pred1)
print("Classification Report:\n", class_report1)
conf_matrix1 = confusion_matrix(y_val, y_pred1)
print("\nConfusion Matrix:")
print(conf_matrix1)

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.76      0.74       525
           1       0.53      0.64      0.58       624
           2       0.69      0.70      0.70       604
           3       0.88      0.94      0.91       714
           4       0.99      1.00      0.99       837
           5       0.56      0.43      0.49       532
           6       0.59      0.49      0.54       523

    accuracy                           0.74      4359
   macro avg       0.71      0.71      0.71      4359
weighted avg       0.73      0.74      0.73      4359


Confusion Matrix:
[[399 114   2   1   0   5   4]
 [113 398  12   4   0  59  38]
 [  6  17 421  46   5  44  65]
 [  0   1  29 672   0   1  11]
 [  0   2   0   2 833   0   0]
 [ 25 150  65   4   0 231  57]
 [  8  73  78  37   0  71 256]]
