Logistic Regression

Best score 0.85

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [2]:
train = pd.read_csv('Data/selected_train.csv')
test = pd.read_csv('Data/selected_test.csv')
val = pd.read_csv('Data/selected_val.csv')

In [3]:
X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [8]:
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga' ],
    'max_iter': [500, 1000, 1500, 2000, 2500]
}

logistic = LogisticRegression(random_state=1)

grid_search = GridSearchCV(estimator=logistic, param_grid=param_grid, cv=3, verbose=2, n_jobs=-1)


grid_search.fit(X_train, y_train)

print("Best parameters found: ", grid_search.best_params_)
print("Best score found: ", grid_search.best_score_)

Fitting 3 folds for each of 120 candidates, totalling 360 fits
Best parameters found:  {'C': 1, 'max_iter': 500, 'penalty': 'l1', 'solver': 'saga'}
Best score found:  0.8459740020514226


In [11]:
log = LogisticRegression(random_state=1, C = 1, max_iter= 500, penalty= 'l1', solver='saga')
log.fit(X_train, y_train)
predictions = log.predict(X_val)
print('Classification report:\n' , classification_report(y_val, predictions))
print('Confusion matrix: \n', confusion_matrix(y_val, predictions))


Classification report:
               precision    recall  f1-score   support

           0       0.90      0.92      0.91       525
           1       0.84      0.82      0.83       624
           2       0.80      0.78      0.79       604
           3       0.90      0.94      0.92       714
           4       0.99      1.00      0.99       837
           5       0.68      0.73      0.70       532
           6       0.70      0.64      0.67       523

    accuracy                           0.85      4359
   macro avg       0.83      0.83      0.83      4359
weighted avg       0.85      0.85      0.85      4359

Confusion matrix: 
 [[481  39   0   0   0   3   2]
 [ 51 511   1   0   0  54   7]
 [  2   1 469  60   4  22  46]
 [  0   0  35 671   1   0   7]
 [  1   0   0   1 834   1   0]
 [  0  48  16   2   0 387  79]
 [  0   9  63  10   1 104 336]]
