Logistic Regression

Best score 0.85

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

In [2]:
train = pd.read_csv('Data/train_with_BMI.csv')
test = pd.read_csv('Data/test_with_BMI.csv')
val = pd.read_csv('Data/val_with_BMI.csv')

In [3]:
X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [6]:
param_grid = {
    'penalty': ['l1', 'l2', None],
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'saga', 'lbfgs'  ],
    'max_iter': [100, 500, 1000, 1500, 2000, 2500]
}

logistic = LogisticRegression(random_state=1)

grid_search = GridSearchCV(estimator=logistic, param_grid=param_grid, cv=3, verbose=2, n_jobs=-1)


grid_search.fit(X_train, y_train)

print("Best parameters found: ", grid_search.best_params_)
print("Best score found: ", grid_search.best_score_)

Fitting 3 folds for each of 324 candidates, totalling 972 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done 276 tasks      | elapsed:    7.2s
[Parallel(n_jobs=-1)]: Done 533 tasks      | elapsed:   33.8s
[Parallel(n_jobs=-1)]: Done 816 tasks      | elapsed:  3.1min
[Parallel(n_jobs=-1)]: Done 972 out of 972 | elapsed:  6.4min finished


Best parameters found:  {'C': 100, 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}
Best score found:  0.8506538703679801


c:\Users\ulasz\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Best parameters C = 100, max_iter = 500, penalty = l2, solver=lbfgs

In [7]:
log = LogisticRegression(random_state=1, C = 100, max_iter= 500, penalty= 'l2', solver='lbfgs')
log.fit(X_train, y_train)
predictions = log.predict(X_val)
print('Classification report:\n' , classification_report(y_val, predictions))
print('Confusion matrix: \n', confusion_matrix(y_val, predictions))


Classification report:
               precision    recall  f1-score   support

           0       0.89      0.92      0.91       525
           1       0.84      0.81      0.83       624
           2       0.82      0.77      0.79       604
           3       0.90      0.95      0.92       714
           4       0.99      1.00      0.99       837
           5       0.69      0.73      0.71       532
           6       0.71      0.66      0.69       523

    accuracy                           0.85      4359
   macro avg       0.83      0.83      0.83      4359
weighted avg       0.85      0.85      0.85      4359

Confusion matrix: 
 [[482  38   0   1   0   3   1]
 [ 54 508   1   0   0  52   9]
 [  2   0 467  64   5  21  45]
 [  0   0  29 678   0   0   7]
 [  1   0   0   1 834   1   0]
 [  0  49  16   1   0 387  79]
 [  0  12  59  12   1  93 346]]


c:\Users\ulasz\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
