SVM

Best score 0.86

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [5]:
train = pd.read_csv('Data/train_with_BMI.csv')
test = pd.read_csv('Data/test_with_BMI.csv')
val = pd.read_csv('Data/val_with_BMI.csv')

In [6]:
X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [7]:
param_grid = {
    'C': [ 0.1, 1, 10, 100],
    'gamma': [ 0.1, 0.01, 0.001],
    'kernel': ['linear', 'rbf', 'poly']
}


svm = SVC()


grid_search = GridSearchCV(estimator=svm, param_grid=param_grid, cv=3, verbose=2, n_jobs=-1)


grid_search.fit(X_train, y_train)


print("Best parameters found: ", grid_search.best_params_)
print("Best score found: ", grid_search.best_score_)

Fitting 3 folds for each of 36 candidates, totalling 108 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   42.4s
[Parallel(n_jobs=-1)]: Done 108 out of 108 | elapsed:  3.8min finished


Best parameters found:  {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
Best score found:  0.8633865984821836


Best parameters: C = 10, gamma = 0.01, kerner = rbf

In [8]:
# best model
svm = SVC(C = 10, gamma= 0.01, kernel='rbf')
svm.fit(X_train, y_train)
predictions = svm.predict(X_val)
print('Classification report:\n' , classification_report(y_val, predictions))
print('Confusion matrix: \n', confusion_matrix(y_val, predictions))

Classification report:
               precision    recall  f1-score   support

           0       0.90      0.90      0.90       525
           1       0.83      0.81      0.82       624
           2       0.85      0.80      0.82       604
           3       0.92      0.97      0.94       714
           4       0.99      1.00      1.00       837
           5       0.70      0.73      0.72       532
           6       0.73      0.69      0.71       523

    accuracy                           0.86      4359
   macro avg       0.84      0.84      0.84      4359
weighted avg       0.86      0.86      0.86      4359

Confusion matrix: 
 [[474  46   0   0   0   3   2]
 [ 50 507   0   0   0  60   7]
 [  2   1 485  46   5  22  43]
 [  0   0  17 692   0   0   5]
 [  1   0   0   1 834   0   1]
 [  0  45  20   0   0 391  76]
 [  0  14  51  15   0  83 360]]


In [9]:
svm.score(X_val, y_val)

0.8586831842165634