SVM

Best score 0.86

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [2]:
train = pd.read_csv('Data/selected_train.csv')
test = pd.read_csv('Data/selected_test.csv')
val = pd.read_csv('Data/selected_val.csv')

In [3]:
X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [4]:
param_grid = {
    'C': [ 0.1, 1, 10, 100],
    'gamma': [ 0.1, 0.01, 0.001],
    'kernel': ['linear', 'rbf', 'poly']
}


svm = SVC()


grid_search = GridSearchCV(estimator=svm, param_grid=param_grid, cv=3, verbose=2, n_jobs=-1)


grid_search.fit(X_train, y_train)


print("Best parameters found: ", grid_search.best_params_)
print("Best score found: ", grid_search.best_score_)

Fitting 3 folds for each of 36 candidates, totalling 108 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   29.3s
[Parallel(n_jobs=-1)]: Done 108 out of 108 | elapsed:  2.2min finished


Best parameters found:  {'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}
Best score found:  0.8614593899418908


In [5]:
svm = SVC(C = 100, gamma= 0.01, kernel='rbf')
svm.fit(X_train, y_train)
predictions = svm.predict(X_val)
print('Classification report:\n' , classification_report(y_val, predictions))
print('Confusion matrix: \n', confusion_matrix(y_val, predictions))

Classification report:
               precision    recall  f1-score   support

           0       0.91      0.91      0.91       525
           1       0.83      0.83      0.83       624
           2       0.82      0.78      0.80       604
           3       0.93      0.96      0.94       714
           4       0.99      1.00      1.00       837
           5       0.70      0.72      0.71       532
           6       0.71      0.69      0.70       523

    accuracy                           0.86      4359
   macro avg       0.84      0.84      0.84      4359
weighted avg       0.86      0.86      0.86      4359

Confusion matrix: 
 [[479  40   0   0   0   3   3]
 [ 42 520   1   0   0  56   5]
 [  2   3 473  43   5  20  58]
 [  0   0  25 685   0   0   4]
 [  1   0   0   1 834   1   0]
 [  0  54  20   0   0 384  74]
 [  0  12  55   8   0  87 361]]


In [9]:
svm.score(X_val, y_val)

0.8570773113099335