XGB Classifier

Best score 0.88

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier

In [4]:
train = pd.read_csv('Data/selected_train.csv')
test = pd.read_csv('Data/selected_test.csv')
val = pd.read_csv('Data/selected_val.csv')

In [5]:
X_train = train.drop('NObeyesdad', axis=1)
y_train = train['NObeyesdad']
X_test = test.drop('NObeyesdad', axis=1)
y_test = test['NObeyesdad']
X_val = val.drop('NObeyesdad', axis=1)
y_val = val['NObeyesdad']

In [6]:
param_grid = {
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.1, 0.2],
    'n_estimators': [100, 200, 500, 1000],
    'subsample': [0.5, 0.75, 1.0],
    'colsample_bytree': [0.5, 0.75, 1.0],
}


xgb = XGBClassifier()


grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)


grid_search.fit(X_train, y_train)


print("Best parameters found: ", grid_search.best_params_)
print("Best score found: ", grid_search.best_score_)

Fitting 3 folds for each of 324 candidates, totalling 972 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   17.5s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  8.6min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 18.3min
[Parallel(n_jobs=-1)]: Done 972 out of 972 | elapsed: 29.3min finished


Best parameters found:  {'colsample_bytree': 0.5, 'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 200, 'subsample': 0.75}
Best score found:  0.8840333087064858


In [15]:
final_model = XGBClassifier(random_state = 1, colsample_bytree = 0.5, learning_rate = 0.1, max_depth = 4, n_estimators = 200, 
                            subsample = 0.75)
final_model.fit(X_train, y_train)
pred = final_model.predict(X_val)

print('Classification report:\n' , classification_report(y_val, pred))
print('Confusion matrix: \n', confusion_matrix(y_val, pred))

Classification report:
               precision    recall  f1-score   support

           0       0.94      0.91      0.92       525
           1       0.83      0.88      0.85       624
           2       0.87      0.84      0.85       604
           3       0.95      0.96      0.96       714
           4       0.99      1.00      0.99       837
           5       0.76      0.73      0.74       532
           6       0.74      0.77      0.75       523

    accuracy                           0.88      4359
   macro avg       0.87      0.87      0.87      4359
weighted avg       0.88      0.88      0.88      4359

Confusion matrix: 
 [[477  43   0   0   0   3   2]
 [ 30 550   1   0   0  36   7]
 [  2   3 505  23   5  22  44]
 [  0   0  21 686   1   0   6]
 [  1   0   0   1 834   1   0]
 [  0  54  12   0   0 386  80]
 [  0  13  43   9   0  57 401]]
